export const enum SocketEvents
{
    RoomList = "room-list",
    RoomName = "room-name",
    UserList = "user-list",
    SubscribeUserList = "subscribe-user-list",
    UnsubscribeUserList = "unsubscribe-user-list",
    AdminAuth = "admin-auth",
    Result = "result",
    DeleteRoom = "delete-room",
    CreateRoom = "create-room",
    JoinRoom = "join-room",
    RoomDeleted = "room-deleted",
    RoomCreated = "room-created",
    MaxAudioBitrate = "max-audio-bitrate",
    RouterRtpCapabilities = "router-rtp-capabilities",
    CreateWebRtcTransport = "create-webrtc-transport",
    CloseTransport = "close-transport",
    CreateConsumerTransport = "create-consumer-transport",
    CreateProducerTransport = "create-producer-transport",
    ConnectWebRtcTransport = "connect-webrtc-transport",
    Ready = "ready",
    NewUser = "new-user",
    CloseConsumer = "close-consumer",
    PauseConsumer = "pause-consumer",
    ResumeConsumer = "resume-consumer",
    NewConsumer = "new-consumer",
    NewProducer = "new-producer"
}